server1:
  image: tomcat

server2:
  image: tomcat

server3:
  image: tomcat

nginx:
  image: nginx:alpine
  volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  links:
    - server1
    - server2
    - server3
  ports:
    - "80:80"
